apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Billing Api
  description: The official Spotify REST API
spec:
  type: openapi
  lifecycle: production
  owner: kimhong
  definition:
    $text: https://github.com/kimhonggit/firstStageDoc/blob/master/swagger.yaml