apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Billing-Api"
  description: "this is my first Documentation"
  annotations:
    github.com/project-slug: kimhonggit/firstStageDoc
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: "backstage"
